name: alsharq
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  awesome_notifications: ^0.7.4+1
  firebase_messaging: ^14.6.8
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.3.3
  sqflite: ^2.2.8+4
  share_plus: ^7.2.1
  awesome_dialog: ^3.1.0
  jiffy: ^6.2.1
  url_launcher: ^6.1.14
  fluttertoast: ^8.2.4
  lottie: ^2.6.0
  confetti: ^0.7.0
  introduction_screen: ^3.1.12
  country_codes: ^2.2.0
  country_icons: ^2.0.0
  flutter_svg: ^1.1.6
  audioplayers: ^5.2.1
  video_player: ^2.7.2
  chewie: 1.7.1
  loading_overlay: ^0.3.0

  flutter_animate: ^4.2.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  cached_network_image: ^3.2.3
  swipe_image_gallery: ^0.8.0

  flick_video_player: ^0.9.0
  syncfusion_flutter_pdfviewer: ^22.2.12
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#  flutter_native_splash:
#flutter_native_splash:
#  color: "#f8ece3"
#  image: "assets/images/splash.png"
#  android_12:
#    image: assets/images/splash_android12.png
#    image_dark: assets/images/splash_android12.png
#    color: "#f8ece3"
#    icon_background_color: "#f8ece3"
#    icon_background_color_dark: "#f8ece3"
#  # dart run flutter_native_splash:create

#  flutter_launcher_icons:
#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/images/icon.png"
#  min_sdk_android: 23
#  adaptive_icon_background: "#ffffff"
#  adaptive_icon_foreground: "assets/images/icon.png"
#  # flutter pub run flutter_launcher_icons

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/images/intro/
    - assets/images/icons/

  fonts:
    - family: Almaria
      fonts:
        - asset: assets/fonts/Almaria/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almaria/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almaria/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almaria/Almarai-ExtraBold.ttf
          weight: 800
    - family: DG
      fonts:
        - asset: assets/fonts/DG/DG-Thin.ttf
          weight: 300
        - asset: assets/fonts/DG/DG-Regular.ttf
          weight: 500
        - asset: assets/fonts/DG/DG-Bold.ttf
          weight: 700

