name: alsharq
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  awesome_notifications: ^0.10.0
  firebase_messaging: ^15.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.7.0
  sqflite: ^2.4.1
  share_plus: ^10.1.4
  awesome_dialog: ^3.2.1
  jiffy: ^6.3.2
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.10
  lottie: ^3.3.1
  confetti: ^0.8.0
  introduction_screen: ^3.1.14
  country_codes: ^3.2.0+1
  country_icons: ^3.0.0
  flutter_svg: ^2.0.17
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  chewie: ^1.10.0
  loading_overlay: ^0.4.2

  flutter_animate: ^4.5.2
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.4
  cached_network_image: ^3.4.1
  swipe_image_gallery: ^0.10.1

  flick_video_player: ^0.9.0
  syncfusion_flutter_pdfviewer: ^28.2.9
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

#  flutter_native_splash:
#flutter_native_splash:
#  color: "#f8ece3"
#  image: "assets/images/splash.png"
#  android_12:
#    image: assets/images/splash_android12.png
#    image_dark: assets/images/splash_android12.png
#    color: "#f8ece3"
#    icon_background_color: "#f8ece3"
#    icon_background_color_dark: "#f8ece3"
#  # dart run flutter_native_splash:create

#  flutter_launcher_icons:
#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/images/icon.png"
#  min_sdk_android: 23
#  adaptive_icon_background: "#ffffff"
#  adaptive_icon_foreground: "assets/images/icon.png"
#  # flutter pub run flutter_launcher_icons

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/images/intro/
    - assets/images/icons/

  fonts:
    - family: Almaria
      fonts:
        - asset: assets/fonts/Almaria/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almaria/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almaria/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almaria/Almarai-ExtraBold.ttf
          weight: 800
    - family: DG
      fonts:
        - asset: assets/fonts/DG/DG-Thin.ttf
          weight: 300
        - asset: assets/fonts/DG/DG-Regular.ttf
          weight: 500
        - asset: assets/fonts/DG/DG-Bold.ttf
          weight: 700

